from PySide6.QtWidgets import QDialog, QWidget, QGroupBox, QScrollArea, QVBoxLayout, QTableWidget, QAbstractItemView
from PySide6.QtCharts import QChart, QLineSeries, QDateTimeAxis, QValueAxis, QChartView, QBarSeries
from PySide6.QtCore import Qt
from PySide6.QtGui import QFont

class StockInfoForecasts(QDialog):
    def __init__(self):
        super().__init__()
        self.setStyleSheet('background-color: deepskyblue')
        self.chart_groupbox = QGroupBox(self)
        self.chart_groupbox.setTitle("Charts and Graphs")
        self.chart_groupbox.setGeometry(0, 0, 1300, 600)
        self.chart_groupbox.content_container = QScrollArea(self)
        self.prediction_chart_widget = QWidget()
        self.prediction_chart_widget.resize(1300, 2000)
        self.prediction_chart_widget.setLayout(QVBoxLayout())
        self.chart_groupbox.content_container.setWidget(self.prediction_chart_widget)
        self.chart_groupbox.content_container.setGeometry(5, 15, 1290, 650)
        self.ptchart = QChart()
        ptlineseries = QLineSeries()
        ptlineseries.setName("stock")
        self.ptchart.addSeries(ptlineseries)
        x_axis = QDateTimeAxis()
        x_axis.setTickCount(7)
        x_axis.setFormat("MM-dd-yyyy")
        x_axis.setTitleText("Date")
        x_axis.setVisible(True)
        self.ptchart.addAxis(x_axis, Qt.AlignmentFlag.AlignBottom)
        ptlineseries.attachAxis(x_axis)
        y_axis = QValueAxis()
        self.ptchart.addAxis(y_axis, Qt.AlignmentFlag.AlignLeft)
        ptlineseries.attachAxis(y_axis)
        self.ptchartview = QChartView(self.ptchart)
        self.pt_groupbox = QGroupBox(self.prediction_chart_widget)
        self.pt_groupbox.setTitle("Analyst Price Targets")
        self.pt_groupbox.setGeometry(10, 10, 1200, 350)
        self.ptchartview.setParent(self.pt_groupbox)
        self.ptchartview.setGeometry(10, 15, 800, 300)
        self.ptchartview.setVisible(True)
        self.pt_label_container = QWidget(self.pt_groupbox)
        self.pt_label_container.setStyleSheet('background-color: white')
        self.pt_label_container.setGeometry(820, 22, 350, 285)
        self.pt_label_container.setLayout(QVBoxLayout())
        self.qtr_earnings_chart = QChart()
        self.qtr_earnings_chart.setTitle("Quarterly EPS")
        self.qtr_earnings_barseries = QBarSeries()
        self.qtr_earnings_barseries.setName("Earnings")
        self.qtr_earnings_chart.addSeries(self.qtr_earnings_barseries)
        self.qtr_earnings_groupbox = QGroupBox(self.prediction_chart_widget)
        self.qtr_earnings_groupbox.setTitle("Earnings History and Projections")
        self.qtr_earnings_groupbox.setGeometry(10, 370, 1200, 350)
        self.qtr_earnings_chartview = QChartView(self.qtr_earnings_chart)
        self.qtr_earnings_chartview.setParent(self.qtr_earnings_groupbox)
        self.qtr_earnings_chartview.setVisible(True)
        self.qtr_earnings_chartview.setGeometry(10, 15, 800, 300)
        self.qtr_earnings_table = QTableWidget(self.qtr_earnings_groupbox)
        self.qtr_earnings_table.setGeometry(820, 20, 350, 290)
        self.qtr_earnings_table.setEditTriggers(QAbstractItemView.EditTrigger.NoEditTriggers)
        self.qtr_earnings_table.setFont(QFont('arial', 10))
        self.qtr_earnings_table.setStyleSheet('background-color: white;')
        self.qtr_revtrend_chart = QChart()
        self.qtr_revtrend_chart.setTitle("Quarterly Revenue Trend")
        self.qtr_revtrend_barseries = QBarSeries()
        self.qtr_revtrend_chart.addSeries(self.qtr_revtrend_barseries)
        self.qtr_revtrend_gb = QGroupBox(self.prediction_chart_widget)
        self.qtr_revtrend_gb.setTitle("Revenue History and Projections")
        self.qtr_revtrend_gb.setGeometry(10, 730, 1200, 350)
        self.qtr_revtrend_chartview = QChartView(self.qtr_revtrend_chart)
        self.qtr_revtrend_chartview.setParent(self.qtr_revtrend_gb)
        self.qtr_revtrend_chartview.setVisible(True)
        self.qtr_revtrend_chartview.setGeometry(10, 15, 800, 300)
        self.qtr_revtrend_label_container = QWidget(self.qtr_revtrend_gb)
        self.qtr_revtrend_label_container.setGeometry(820, 20, 350, 290)
        self.qtr_revtrend_label_container.setStyleSheet('background-color: white;')
        self.qtr_revtrend_label_container.setLayout(QVBoxLayout())
        self.yr_earnings_chart = QChart()
        self.yr_earnings_chart.setTitle("Yearly EPS")
        self.yr_earnings_barseries = QBarSeries()
        self.yr_earnings_barseries.setName("Earnings")
        self.yr_earnings_chart.addSeries(self.yr_earnings_barseries)
        self.yr_earnings_groupbox = QGroupBox(self.prediction_chart_widget)
        self.yr_earnings_groupbox.setTitle("Earnings History and Projections")
        self.yr_earnings_groupbox.setGeometry(10, 1090, 1200, 350)
        self.yr_earnings_chartview = QChartView(self.yr_earnings_chart)
        self.yr_earnings_chartview.setParent(self.yr_earnings_groupbox)
        self.yr_earnings_chartview.setVisible(True)
        self.yr_earnings_chartview.setGeometry(10, 15, 800, 300)
        self.yr_earnings_label_container = QWidget(self.yr_earnings_groupbox)
        self.yr_earnings_label_container.setGeometry(820, 20, 350, 290)
        self.yr_earnings_label_container.setStyleSheet('background-color: white;')
        self.yr_earnings_label_container.setLayout(QVBoxLayout())
        self.yr_revtrend_chart = QChart()
        self.yr_revtrend_chart.setTitle("Yearly Revenue Trend")
        self.yr_revtrend_barseries = QBarSeries()
        self.yr_revtrend_chart.addSeries(self.yr_revtrend_barseries)
        self.yr_revtrend_gb = QGroupBox(self.prediction_chart_widget)
        self.yr_revtrend_gb.setTitle("Revenue History and Projections")
        self.yr_revtrend_gb.setGeometry(10, 1450, 1200, 360)
        self.yr_revtrend_chartview = QChartView(self.yr_revtrend_chart)
        self.yr_revtrend_chartview.setParent(self.yr_revtrend_gb)
        self.yr_revtrend_chartview.setVisible(True)
        self.yr_revtrend_chartview.setGeometry(10, 15, 800, 300)
        self.yr_revtrend_label_container = QWidget(self.yr_revtrend_gb)
        self.yr_revtrend_label_container.setGeometry(820, 20, 350, 290)
        self.yr_revtrend_label_container.setStyleSheet('background-color: white;')
        self.yr_revtrend_label_container.setLayout(QVBoxLayout())
