name: windows build

on:
  push:
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Conda
        uses: s-weigand/setup-conda@v1
      - name: Install TA-Lib
        run: |
          conda install -c conda-forge ta-lib
      - name: Run PyInstaller
        run: |
          pip install pyinstaller
          pip install Pillow
          python -m PyInstaller yftest.spec
      - name: Assemble Linux Build
        run: |
          cp assets dependencies fonts icons splashscreen-images dist
          zip linux-build.zip dist
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
            name: linux-build
            path: linux-build.zip
  build-windows:
    runs-on: windows-latest
    needs: build-linux
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Download Artifcat
        uses: actions/download-artifact@v2
        with: 
          name: linux-build
      - name: Setup Conda
        uses: s-weigand/setup-conda@v1
      - name: Install TA-Lib
        run: |
          conda install -c conda-forge ta-lib
      - name: Run PyInstaller
        run: |
          pip install pyinstaller
          pip install Pillow
          python -m PyInstaller yftest.spec
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
            name: windows-build
            path: dist/yftest.exe
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/heads/')
        with:
          tag_name: ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false
          files: |
            linux-build.zip
            dist/yftest.exe
        
      
