name: linux build

on:
  push:
jobs:
  build-windows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Conda
        uses: s-weigand/setup-conda@v1
