name: build

on:
  push:
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Conda
        uses: s-weigand/setup-conda@v1
      - name: Install TA-Lib
        run: |
          conda install -c conda-forge ta-lib
      - name: Run PyInstaller
        run: |
          pip install pyinstaller
          pip install Pillow
          python -m PyInstaller yftest.spec
      - name: Assemble Linux Build
        run: |
          cp -R assets dependencies fonts icons splashscreen-images dist
          zip -r linux-build.zip dist
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
            name: linux-build
            path: linux-build.zip
  build-windows:
    runs-on: windows-latest
    needs: build-linux
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Download Artifcat
        uses: actions/download-artifact@v2
        with: 
          name: linux-build
      - name: Setup Conda
        uses: s-weigand/setup-conda@v1
      - name: Install TA-Lib
        run: |
          conda install -c conda-forge ta-lib
      - name: Run PyInstaller
        run: |
          conda uninstall Pillow
          python -m pip install Pillow
          conda install -c conda-forge pyinstaller pandas holidays beautifulsoup4 scipy tensorflow matplotlib mplfinance
          python -m pip install yahooquery holidays PySide6 PySide6-Addons PySide6-Essentials
          
          python -m PyInstaller --add-data "c:/miniconda/lib/site-packages/PySide6/plugins;PySide6/plugins/" --onefile --noconsole --icon=wsb.jpg yftest.py
      - name: Assemble Windows Build
        run: |
          Copy-Item -Path "assets" -Destination "dist" -Recurse
          Copy-Item -Path "dependencies" -Destination "dist" -Recurse
          Copy-Item -Path "fonts" -Destination "dist" -Recurse
          Copy-Item -Path "icons" -Destination "dist" -Recurse
          Copy-Item -Path "splashscreen-images" -Destination "dist" -Recurse
          Compress-Archive dist windows-build.zip
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
            name: windows-build
            path: dist/yftest.exe
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/heads/')
        with:
          tag_name: ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false
          files: |
            linux-build.zip
            windows-build.zip
        
      
